services:
  web:
    build: .
    container_name: nykaa_app
    command: gunicorn nykaa_backend.wsgi:application --bind 0.0.0.0:8000 --timeout 120
    volumes:
      - ./nykaa_backend:/app
      - ./nykaa_backend/media:/app/media
    ports:
      - "8004:8000"
    env_file:
      - .env.dev
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: nykaa_shop
      MYSQL_ROOT_PASSWORD: 9019860150
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: